# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/aidl/work/examples/04_Object_Detection_Based_On-Device_AI/gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1191, 724)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cameraFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraFrame.sizePolicy().hasHeightForWidth())
        self.cameraFrame.setSizePolicy(sizePolicy)
        self.cameraFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cameraFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cameraFrame.setObjectName("cameraFrame")
        self.lblRoadCamera = QtWidgets.QLabel(self.cameraFrame)
        self.lblRoadCamera.setEnabled(True)
        self.lblRoadCamera.setGeometry(QtCore.QRect(0, 0, 1160, 650))
        self.lblRoadCamera.setMinimumSize(QtCore.QSize(640, 480))
        self.lblRoadCamera.setStyleSheet("background-color: black;\n"
"color: white;\n"
"border: 2px solid gray;")
        self.lblRoadCamera.setFrameShape(QtWidgets.QFrame.Box)
        self.lblRoadCamera.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRoadCamera.setObjectName("lblRoadCamera")
        self.lblDriverCamera = QtWidgets.QLabel(self.cameraFrame)
        self.lblDriverCamera.setGeometry(QtCore.QRect(820, 390, 320, 240))
        self.lblDriverCamera.setStyleSheet("background-color: black;\n"
"color: white;\n"
"border: 1px solid gray;")
        self.lblDriverCamera.setFrameShape(QtWidgets.QFrame.Box)
        self.lblDriverCamera.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDriverCamera.setObjectName("lblDriverCamera")
        self.warningFrame = QtWidgets.QFrame(self.cameraFrame)
        self.warningFrame.setGeometry(QtCore.QRect(380, 210, 411, 231))
        self.warningFrame.setStyleSheet("QFrame {\n"
"    background-color: rgba(180, 0, 0, 170);\n"
"    border: 1px solid red;\n"
"    border-radius: 20px;\n"
"}")
        self.warningFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.warningFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.warningFrame.setObjectName("warningFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.warningFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblWarningText = QtWidgets.QLabel(self.warningFrame)
        self.lblWarningText.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"}")
        self.lblWarningText.setAlignment(QtCore.Qt.AlignCenter)
        self.lblWarningText.setObjectName("lblWarningText")
        self.verticalLayout_2.addWidget(self.lblWarningText)
        self.txtStmLog = QtWidgets.QPlainTextEdit(self.cameraFrame)
        self.txtStmLog.setGeometry(QtCore.QRect(30, 560, 191, 71))
        self.txtStmLog.setStyleSheet("QPlainTextEdit {\n"
"    background-color: rgba(30, 30, 30, 190);\n"
"    color: #ffb000;\n"
"    border: 1px solid orange;\n"
"    font-size: 14px;\n"
"}")
        self.txtStmLog.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtStmLog.setReadOnly(True)
        self.txtStmLog.setObjectName("txtStmLog")
        self.verticalLayout.addWidget(self.cameraFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1191, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblRoadCamera.setText(_translate("MainWindow", "Road Camera"))
        self.lblDriverCamera.setText(_translate("MainWindow", "Driver Camera"))
        self.lblWarningText.setText(_translate("MainWindow", "졸음 경고!\n"
"눈을 떠주세요"))
